//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layering1.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tb
    {
        public int idUser { get; set; }
        public string NameUser { get; set; }
        public int Age { get; set; }
        public string Enrollment { get; set; }
        public string FirstDose { get; set; }
        public string SecondDose { get; set; }
        public bool Vaccinated { get; set; }
        public bool RoleUser { get; set; }
    }
}
